CREATE TABLE templates (
  id INT PRIMARY KEY NOT NULL,
  id_parent INT NOT NULL DEFAULT 0,
  is_parent BOOLEAN NOT NULL DEFAULT FALSE,
  title TEXT NOT NULL,
  color VARCHAR(7) NOT NULL,
  abr VARCHAR(2) NOT NULL,
  data JSON NOT NULL,
  fields JSON
);

